# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42a600d1ea648e671c91162fd3a72c04c36ccdf45484d0aed1a2b775a0ddf39740667951be009ba1d21387d99b0c2ede88d53f4238ccaea069912d31c1865e1e

test:
  secret_key_base: 8540596971a37df309da05e4d5df937334f01cea7a0638085a3e62ac8a3eca9116ff4eadbf8531beecf3ab20d53dbf4bd5de14c97bb8a43b9d1d197d88487278

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
