# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f59ec5df77d5ef08a0b731770e316fbba6afce50f8d7fe1b457bd92536525628d4f80a102d8092a9e042d93bada1d39c700708ad67bd3b8c8c60bccae434078

test:
  secret_key_base: f15a0328ca45b98698d2095e840072a52af8c76288fc1d8efc8904f9bb0bb561a7f8530cbd5c5f93d5603b39ebe4f0ff971098e4c604c6a018006e5991299804

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
